### ISSUE TITLE
README.md is incorrect on default_values?

### ISSUE THREAD

**Issue by combsco** [Nebo15/multiverse#13]
README states you can use :latest and :edge channels as away of controlling the versions. However, :edge doesn't exist in ~> 2.0.0.

Possible values are :latest and :oldest

```
** (ArgumentError) invalid Multiverse.Adapters.ISODate :default_version config value, possible values: :latest, :oldest, got: :edge
    lib/multiverse/adapters/iso_date.ex:44: Multiverse.Adapters.ISODate.init/2
    lib/multiverse/adapter.ex:68: Multiverse.Adapter.compile_config!/2
    lib/multiverse.ex:60: Multiverse.init/1
```

**Comment by AndrewDryga** [comment]
I guess readme is not clear enough. Channel and `default_version` are totally different. Channel is a value that API client can use instead of specifying a version (send it in header), `default_version` can have one of two values which specced in docs.

**Comment by AndrewDryga** [comment]
@combsco so just try setting `default_version: :latest` instead.

**Comment by AndrewDryga** [comment]
I'm closing this issue for now, feel free to reply here and ask any questions :)
