### ISSUE TITLE
Version header on the response

### ISSUE THREAD

**Issue by archseer** [Nebo15/multiverse#5]
Would be nice to have a version header in the response.

- If no version was specified, I'd default to the latest one (but not the latest date, the latest date specified in the gate configuration).

- If a version was specified or the error callback loaded a different version, then I'd display that (good sanity check for users that they actually got the version they requested).

**Comment by AndrewDryga** [comment]
We can't actually fallback to the latest version specified because then it won't be possible to schedule a version release. 

Now it's possible to have version set "in future" and do a manual QA before everybody else would get access to it.

**Comment by AndrewDryga** [comment]
Now you can write a custom adapter to handle those edge cases whatever you like. I'll close this issue for now, but feel free to ask any additional questions here.
